services:
  - type: web
    name: floodbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false 